#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.02           \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xffc9a8fa     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           on             \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               15             \
    left_padding                 15             \
    right_padding                15             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               ctrl           \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Set top padding based on whether running on the notched screen or not
#yabai -m signal --add event=display_changed action="python3 ~/.config/yabai/set_padding.py"
#python3 ~/.config/yabai/set_padding.py

# Applications that are tiled by yabai
#applications="(Google Chrome|Code|iTerm2)"
#yabai -m rule --add app!="^${applications}$" manage=off

applications="()"
yabai -m rule --add app!="^${applications}$" manage=off

# float apps deny-list
#yabai -m rule --add app="^Calendar|Slack|Mail|Spotify|Messages|System Preferences|Cisco AnyConnect Secure Mobility Client$" sticky=on manage=off

#yabai -m rule --add app="^IntelliJ IDEA$" manage=off
#yabai -m rule --add app="^IntelliJ IDEA$" title="( – )" manage=on

#yabai -m rule --add app="^Amazon Chime$" manage=off
#yabai -m rule --add app="^Amazon Chime$" title="(:)" manage=on

# Shadow for floating windows
#yabai -m config window_shadow float

# focus window after active space changes
#yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
#yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
